### PR TITLE
DAC6-2566 : Added reporterType page

### PR DESCRIPTION
**Pull request by AashuChauhanHmrc**

### CODE REVIEW

**Review by matthewharris1 — DISMISSED** [review]
Happy to approve this but @AashuChauhanHmrc please make sure you amend your commit messages to be specific to what that commit is doing

**Review by ers2015112 — DISMISSED** [review]
LGTM though applied migrations file could be removed

**Review by ers2015112 — CHANGES_REQUESTED** [review]
Remove applied migrations file otherwise looks OK

**Review by koladeadewuyi — DISMISSED** [review]

**Comment by awarhade** [comment]
2567 already pulled changes from this branch , so closing

**Pull request closed without merging**
